### ISSUE TITLE
npm package broken when requirejs is installed

### ISSUE THREAD

**Issue by zvxryb** [MatthewJA/Coffeequate#115]
Steps to reproduce:

1. `mkdir coffeequate-test && pushd coffeequate-test`
2. `npm install requirejs`
3. `npm install coffeequate`

Installation will fail at the postinstall hook `cake all`

On a side note, I noticed that the entire source tree is shipped in the npm package and built on the client side.  I think this should be done in a prepublish script, as per the [npm docs](https://docs.npmjs.com/misc/scripts#common-uses):

> If you need to perform operations on your package before it is used, in a way that is not dependent on the operating system or architecture of the target system, use a prepublish script. This includes tasks such as:
> 
> * Compiling CoffeeScript source code into JavaScript.
> * Creating minified versions of JavaScript source code.
> * Fetching remote resources that your package will use.

The minified source should be explicitly packaged using the [files](https://docs.npmjs.com/files/package.json#files) field so that the rest of the source tree isn't packaged.

**Comment by MatthewJA** [comment]
I shall restructure things on the `npm` end!

**Comment by MatthewJA** [comment]
Restructured! Hopefully that works nicely now.

**Comment by zvxryb** [comment]
Works perfectly
