### ISSUE TITLE
Lack of coordination between abstract classes and implementations

### ISSUE THREAD

**Issue by bshlgrs** [MatthewJA/Coffeequate#78]
Coffeequate currently mixes together two conflicting styles of OO design:

- Write code which expects to act on the classes you defined. Eg, have wrappers around numeric values and so on. In this paradigm, you define abstract classes with default behaviours and don't check for the existence of functions before calling them.
- Write code which mixes in other kinds of objects. Check for the existence of functions before calling them.

We should use the first style, but we have traces of the second style. For example, Pow.coffee lines 183 to 188 should be replaced by just `@children.left.simplify()`, because everything which we allow to be the child of a Pow node has that method defined: if it can't be simplified, it will just copy itself. Maybe that code was written back when we allowed primitive JS numbers to be in coffeequate expressions.

We should rewrite this kind of stuff where we see it, and not write more of it.

**Comment by MatthewJA** [comment]
Resolved by #113
